permalink: /:year/:month/:day/:title.html
markdown: kramdown
pygments: true

kramdown:
  input: GFM

# 作者信息
author: 
  name: 龚大鹏
  email: anthozoan77@gmail.com
  #link: http://yansu.org
  #weibo: http://weibo.com/yansu0711
  github: http://github.com/byr-gdp

# 站点信息
title: 龚大鹏的博客 
description: 龚大鹏的博客
#url: http://yansu.org
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar:  ./assets/img/avatar.png
favicon: ./assets/img/avatar.png
# Sidebar filter
# Choose 'tag' or 'category' as filter in sidebar.
filter: 'category'

# google analytics 设置
# ga:
  # id: UA-54767140-1
 # url: yansu.org

# disqus 设置
disqus:
  shortname: byrgdpgithubio